jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        SeerUK\Security\AccountBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: SeerUKSecurityAccountBundle:User, property: account_name }

    firewalls:
        login:
            pattern:  ^/Account/Login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /Account/Login/Check
                login_path: /Account/Login
            logout:
                path:   /Account/Logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/Admin, roles: ROLE_ADMIN }
