# ===========================
#  Home Controllers
# ===========================
SeerUK_Home:
    pattern:  /
    defaults: { _controller: SeerUKPortfolio:Home:Home }


# ===========================
#  Blog Controllers
# ===========================
SeerUK_BlogHome:
    pattern:  /Blog/Home
    defaults: { _controller: SeerUKPortfolio:Blog:Home }

SeerUK_BlogArticle:
    pattern:  /Blog/Article/{article}
    defaults: { _controller: SeerUKPortfolio:Blog:Article }