# ===========================
#  Home Controllers
# ===========================
SeerUK_Home:
    pattern:  /
    defaults: { _controller: SeerUKPortfolioBundle:Home:Home }


# ===========================
#  Blog Controllers
# ===========================
SeerUK_BlogHome:
    pattern:  /Blog/Home
    defaults: { _controller: SeerUKPortfolioBundle:Blog:Home }

SeerUK_BlogArticle:
    pattern:  /Blog/Article/
    defaults: { _controller: SeerUKPortfolioBundle:Blog:Article }