# ===========================
#  Home Controllers
# ===========================
SeerUK_Home:
    pattern:  /
    defaults: { _controller: SeerUKPortfolioBundle:Home:Home }

# ===========================
#  Administrative Pages
# ===========================
SeerUK_AccountLogin:
    pattern: /Account/Login
    defaults: { _controller: SeerUKPortfolioBundle:Account:Login }

# ===========================
#  Administrative Pages
# ===========================
SeerUK_AdminHome:
    pattern: /Admin
    defaults: { _controller: SeerUKPortfolioBundle:Admin:Home }

# ===========================
#  Blog Controllers
# ===========================
SeerUK_BlogHome:
    pattern:  /Blog/Home
    defaults: { _controller: SeerUKPortfolioBundle:Blog:Home }

SeerUK_BlogArticle:
    pattern:  /Blog/Article/
    defaults: { _controller: SeerUKPortfolioBundle:Blog:Article }
